### ISSUE TITLE
BUG 🐞: Crash on launch

### ISSUE THREAD

**Issue by sammcj** [ajayd-san/gomanagedocker#18]
**Describe the bug**

The application crashes upon launch:

```
panic: runtime error: slice bounds out of range [:1] with capacity 0────────────────────────────────────────────────────────────────────────────────────────────────────┘

                                                                    goroutine 13 [running]:
                                                                                           github.com/ajayd-san/gomanagedocker/tui.transformListNames({0xfe5320, 0x0, 0x0})
                                                                                                                                                                           	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/types.go:241 +0x2df
                                                                                                                                          github.com/ajayd-san/gomanagedocker/tui.imageItem.getName(...)
                           	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/types.go:76
                                                                                                                                                                   github.com/ajayd-san/gomanagedocker/tui.MainModel.fetchNewData.func1()
                                                            	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/mainModel.go:730 +0x11f
                                  created by github.com/ajayd-san/gomanagedocker/tui.MainModel.fetchNewData in goroutine 1
                                                                                                                          	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/mainModel.go:724 +0x345
                                                                                                  #
```

The crash also left the terminal in a very borked state, I had a similar issue with my [gollama](https://github.com/sammcj/gollama) application and I think the fix was to add a `fmt.Print("\033[H\033[2J")` upon exit to reset the term 😅 

**To Reproduce**
Steps to reproduce the behaviour:

This I'm not sure about actually but my specs below.

```shell
go install github.com/ajayd-san/gomanagedocker@HEAD
gomanagedocker
```

**Expected behaviour**

No crash to occur

**Screenshots**
N/A

**Server (please complete the following information):**

 - OS: Fedora 40
 - gmd Version: 1.3
 - Docker: 27.0.3, build 7d4bcd8
 - nvidia-container-toolkit: 1.16.0

**Additional context**

**Comment by ashishkhuraishy** [comment]
this is beacuse of dangling images in local machine, had this same issue on my local - will create a pr for the fix

**Comment by ajayd-san** [comment]
@sammcj thanks for bringing to my notice. @ashishkhuraishy  worked on a hotfix and it will be live soon!

**Comment by ajayd-san** [comment]
@sammcj I've pushed a hotfix to address this issue. Try installing from source again, You shouldn't have any issues. 

@ashishkhuraishy thanks for your fix!

**Comment by sammcj** [comment]
That fixed it! Thanks to you both :)
